version: '3.8'

services:
  nest-crud-api:
    build: .
    container_name: nest-crud-api
    depends_on:
      - nest-crud-db
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes: 
      - .:/app

  nest-crud-db:
    container_name: nest-crud-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
       - db-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    
volumes:
  db-data: